[package]
name = "nlc"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
edition = "2018"

[dependencies]
packed_simd = "0"
num-format  = "0"

[profile.release]
lto = true
codegen-units = 1
debug = false
panic = "abort"
