[package]
name = "nlc"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
edition = "2018"

[dependencies]
packed_simd = { version = "0", features = ["into_bits"] }
num-format = "0"

[profile.release]
lto = true
codegen-units = 1